name: Bug Report
description: Report a bug in @gcko/nx-sonar
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue :white_check_mark:
        Please search GitHub for a similar [issue](https://github.com/gcko/nx-sonar/issues) or [PR](https://github.com/gcko/nx-sonar/pulls) before submitting a new issue.

  - type: textarea
    id: environment
    attributes:
      label: If possible, please provide a reproduction repository you discovered this bug in.
      description: GitHub URL

  - type: dropdown
    id: type_bug
    attributes:
      label: Which area/package is the issue in?
      options:
        - "@gcko/nx-sonar"
        - Astro Docs Site
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: textarea
    id: nx-report
    attributes:
      label: If applicable, please provide the Nx report
      description: Run "npx nx report"

  - type: textarea
    id: exception-or-error
    attributes:
      label: Please provide the exception or error you saw
      render: true

  - type: textarea
    id: other
    attributes:
      label: Other information

  - type: checkboxes
    id: assistance
    attributes:
      label: I would be willing to submit a PR to fix this issue
      description: Assistance is provided if you need help submitting a pull request
      options:
        - label: 'Yes'
        - label: 'No'
