name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  NX_BRANCH: ${{ github.event.number || github.ref_name }}

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.14.0
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    with:
      node-version: 22
      main-branch-name: main
      number-of-agents: 3
      parallel-commands-on-agents: |
        npx nx affected -t lint --parallel --exclude gcko
        npx nx affected -t test --parallel --exclude gcko
        npx nx affected -t build --parallel --exclude gcko

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.14.0
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    with:
      node-version: 22
      number-of-agents: 3
